# Python CircleCI 2.0 configuration file
#
# Source: https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

references:
  container_config_36: &container_config_36
    working_directory: ~/repo
    docker:
      - image: $AWS_ECR_IMAGE_TAG_36
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

  container_config_27: &container_config_27
    working_directory: ~/repo
    docker:
      - image: $AWS_ECR_IMAGE_TAG_27
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - repo-v1-{{ .Branch }}-{{ .Revision }}
        - repo-v1-{{ .Branch }}
        - repo-v1-

  python_requirements_cache_key: &python_requirements_cache_key
    dependencies-v1-{{ checksum "requirements.txt" }}

  python_requirements_backup_cache_key: &python_requirements_backup_cache_key
    dependencies-v1-

  restore_python_dependencies: &restore_python_dependencies
    restore_cache:
      keys:
        - *python_requirements_cache_key
        # fallback to using the latest cache if no exact match is found
        - *python_requirements_backup_cache_key

jobs:
  checkout_code:
    <<: *container_config_36
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: repo-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  python_dependencies_36:
    <<: *container_config_36
    steps:
      - *restore_repo
      - run:
          name: install dependencies
          command: |
            mkdir -p venvs/36
            python -m venv ./venvs/36
            . venvs/36/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - save_cache:
          key: *python_requirements_cache_key
          paths:
            - ./venvs/36

  lint_36:
    <<: *container_config_36
    steps:
      - *restore_repo
      - *restore_python_dependencies
      - run:
          name: run linter
          command: |
            mkdir -p test-reports
            . venvs/36/bin/activate
            python --version
            pylint buzzard --output-format=json > test-reports/pylint.json || true
          when: always

  test_36:
    <<: *container_config_36
    steps:
      - *restore_repo
      - *restore_python_dependencies
      # run tests!
      - run:
          name: run tests
          command: |
            . venvs/36/bin/activate
            pytest --cov=buzzard --cov-report=term --cov-report=xml
            coveralls

      - store_artifacts:
          path: test-reports
          destination: test-reports

  python_dependencies_27:
    <<: *container_config_27
    steps:
      - *restore_repo
      - run:
          name: install dependencies
          command: |
            pip install virtualenv
            mkdir -p venvs/27
            virtualenv venvs/27
            . venvs/27/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - save_cache:
          key: *python_requirements_cache_key
          paths:
            - ./venvs/27

  test_27:
    <<: *container_config_27
    steps:
      - *restore_repo
      - *restore_python_dependencies
      # run tests!
      - run:
          name: run tests
          command: |
            . venvs/27/bin/activate
            pytest --cov=buzzard --cov-report=term --cov-report=xml
            coveralls

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  buzzard:
    jobs:
      - checkout_code
      - python_dependencies_36:
          requires:
            - checkout_code
      - lint_36:
          requires:
            - checkout_code
            - python_dependencies_36
      - test_36:
          requires:
            - checkout_code
            - python_dependencies_36
      - python_dependencies_27:
          requires:
            - checkout_code
      - test_27:
          requires:
            - checkout_code
            - python_dependencies_27
